#!/usr/bin/env bash
#this script displays :
#To infinity and beyond and sleep 3 sec
#and displays I am invincible!!! when receiving a sigterm

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I am invincible!!!'" SIGTERM
done
