#!/usr/bin/env bash

#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

files="$(ls)"

for file in $files
do
	file="$(find "$file" | cut -d- -f2)"
	echo "$file"
done
